main: main.m
	gcc -o main main.m -I /usr/GNUstep/System/Library/Headers -L /usr/GNUstep/System/Library/Libraries/ -lgnustep-base -lgnustep-gui -fconstant-string-class=NSConstantString

clean:
	rm -rf *~ main
