lottery: lottery.m LotteryEntry.m LotteryEntry.h
	gcc -o lottery -I /usr/GNUstep/System/Library/Headers -L /usr/GNUstep/System/Library/Libraries/ -lobjc -lgnustep-base -lgnustep-gui -fconstant-string-class=NSConstantString -fobjc-exceptions lottery.m LotteryEntry.m

clean:
	rm -rf *~ main
