#!/usr/bin/env perl

##### This software is used to create or manage a objective-C project. #####



main: main.m
	gcc -o main main.m -I /usr/GNUstep/System/Library/Headers -L /usr/GNUstep/System/Library/Libraries/ -lgnustep-base -fconstant-string-class=NSConstantString

clean:
	rm -rf *~ main
