######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 8 21:26:01 2011
######################################################################

TEMPLATE = app
TARGET = demo
DEPENDPATH += .
INCLUDEPATH += .

QT += opengl

# Input
HEADERS += GLWidget.h qtglut.h
SOURCES += GLWidget.cpp qtglut.cpp main.cpp
